version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: doc-assistant
    container_name: doc-assistant
    restart: unless-stopped
    working_dir: /var/www/docAssistant
    volumes:
      - .:/var/www/docAssistant
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "9000:9000"

  db:
    image: mysql:5.7
    container_name: doc-assistant-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: